config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :accounts
  resources :bottles
  resources :sujetos
  devise_for :users

  root "accounts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/movement.rb
class Movement < ApplicationRecord
  paginates_per 50
  belongs_to :account


  validates_numericality_of :amount, greater_than_or_equal_to: 0
  validates :description, :presence => true

  def tipo
  if movement_type == 1
    "Débito"
  else
    "Crédito"
  end
end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: %i[ show edit update destroy ]

  # GET /movements or /movements.json
  def index
    @movements = Movement.all
    @movements = @movements.page(params[:page] || 1)
    @movements = @movements.where(:account_id => params[:account_id]) unless params[:account_id].blank?
    @movements = @movements.order((params[:by] || "amount") + " " + (params[:order] || "asc"))
    @movements = @movements.order((params[:by] || "description") + " " + (params[:order] || "asc"))
  end

  # GET /movements/1 or /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements or /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: "Movement was successfully created." }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1 or /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: "Movement was successfully updated." }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1 or /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: "Movement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_params
      params.require(:movement).permit(:movement_date, :movement_type, :description, :amount, :account_id)
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_with(model: movement) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
        <% movement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :movement_date %>
    <%= form.datetime_select :movement_date %>
  </div>

  <div class="field">
    <%= form.label :movement_type %>
      <select name="movement[movement_type]">
        <option value="1">Gasto</option>
        <option value="2">Ingreso</option>
      </select>
  </div>



  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.collection_select(:account_id, Account.all, :id, :name) %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movements</h1>

<select name="account_id">
    <option value="">Seleccione cuenta</option>
    <% Account.all.each do | d | %>
      <option value="<%= d.id %>"><%= d.name %></option>
    <% end %>
  </select>
  <input type="submit" />

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Movement date</th>
        <th><%= link_to "Description", movements_path(:sort => true, :by => "Description", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th>Movement type</th>
      <th><%= link_to "Amount", movements_path(:sort => true, :by => "Amount", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
          <td><%= movement.account.name %></td>
        <td><%= movement.movement_date %></td>
          <td><%= movement.description %></td>
        <td><%= movement.tipo %></td>
        <td><%= movement.amount %></td>

        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @movements %>
<br>

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movement date:</strong>
  <%= @movement.movement_date %>
</p>

<p>
  <strong>Movement type:</strong>
  <%= @movement.movement_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movement.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @movement.amount %>
</p>

<p>
  <strong>Account:</strong>
  <%= @movement.account_id %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>