config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :accounts
  resources :bottles
  resources :sujetos
  devise_for :users

  root "accounts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bottle.rb
class Bottle < ApplicationRecord
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: %i[ show edit update destroy ]

  # GET /bottles or /bottles.json
  def index
    @bottles = Bottle.all
  end

  # GET /bottles/1 or /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles or /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: "Bottle was successfully created." }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1 or /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: "Bottle was successfully updated." }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1 or /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: "Bottle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bottle_params
      params.require(:bottle).permit(:name)
    end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/_form.html.erb
<%= form_with(model: bottle) do |form| %>
  <% if bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
        <% bottle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<h1>Editing Bottle</h1>

<%= render 'form', bottle: @bottle %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bottles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bottles.each do |bottle| %>
      <tr>
        <td><%= bottle.name %></td>
        <td><%= link_to 'Show', bottle %></td>
        <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
        <td><%= link_to 'Destroy', bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/new.html.erb
<h1>New Bottle</h1>

<%= render 'form', bottle: @bottle %>

<%= link_to 'Back', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bottle.name %>
</p>

<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>