config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :accounts
  resources :bottles
  resources :sujetos
  devise_for :users

  root "accounts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sujeto.rb
class Sujeto < ApplicationRecord
  paginates_per 5

validates :first_name, :presence => true
validates :last_name, :presence => true
validates :birthday, :presence => true
validates :document_number, :presence => true, :uniqueness => true
validates_numericality_of :document_number, less_than_or_equal_to: 99999999, greater_than_or_equal_to: 1000000


end

app/controllers/sujetos_controller.rb
class SujetosController < ApplicationController
  before_action :set_sujeto, only: %i[ show edit update destroy ]

  # GET /sujetos or /sujetos.json
  def index
    @sujetos = Sujeto.all
    @sujetos = @sujetos.order(:first_name).page(params[:page] || 1)
  end

  # GET /sujetos/1 or /sujetos/1.json
  def show
  end

  # GET /sujetos/new
  def new
    @sujeto = Sujeto.new
  end

  # GET /sujetos/1/edit
  def edit
  end

  # POST /sujetos or /sujetos.json
  def create
    @sujeto = Sujeto.new(sujeto_params)

    respond_to do |format|
      if @sujeto.save
        format.html { redirect_to @sujeto, notice: "Sujeto was successfully created." }
        format.json { render :show, status: :created, location: @sujeto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sujeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sujetos/1 or /sujetos/1.json
  def update
    respond_to do |format|
      if @sujeto.update(sujeto_params)
        format.html { redirect_to @sujeto, notice: "Sujeto was successfully updated." }
        format.json { render :show, status: :ok, location: @sujeto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sujeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sujetos/1 or /sujetos/1.json
  def destroy
    @sujeto.destroy
    respond_to do |format|
      format.html { redirect_to sujetos_url, notice: "Sujeto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sujeto
      @sujeto = Sujeto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sujeto_params
      params.require(:sujeto).permit(:first_name, :last_name, :document_number, :birthday)
    end
end

app/helpers/sujetos_helper.rb
module SujetosHelper
end

app/views/sujetos/_form.html.erb
<%= form_with(model: sujeto) do |form| %>
  <% if sujeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sujeto.errors.count, "error") %> prohibited this sujeto from being saved:</h2>

      <ul>
        <% sujeto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :document_number %>
    <%= form.number_field :document_number %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.datetime_select :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sujetos/edit.html.erb
<h1>Editing Sujeto</h1>

<%= render 'form', sujeto: @sujeto %>

<%= link_to 'Show', @sujeto %> |
<%= link_to 'Back', sujetos_path %>

app/views/sujetos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sujetos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Document number</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sujetos.each do |sujeto| %>
      <tr>
        <td><%= sujeto.first_name %></td>
        <td><%= sujeto.last_name %></td>
        <td><%= sujeto.document_number %></td>
        <td><%= sujeto.birthday %></td>
        <td><%= link_to 'Show', sujeto if can? :show, Sujeto %></td>
        <td><%= link_to 'Edit', edit_sujeto_path(sujeto) %></td>
        <td><%= link_to 'Destroy', sujeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @sujetos %>
<br>

<%= link_to 'New Sujeto', new_sujeto_path %>

app/views/sujetos/new.html.erb
<h1>New Sujeto</h1>

<%= render 'form', sujeto: @sujeto %>

<%= link_to 'Back', sujetos_path %>

app/views/sujetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @sujeto.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @sujeto.last_name %>
</p>

<p>
  <strong>Document number:</strong>
  <%= @sujeto.document_number %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @sujeto.birthday %>
</p>

<%= link_to 'Edit', edit_sujeto_path(@sujeto) %> |
<%= link_to 'Back', sujetos_path %>